import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { FundingProvider } from "../context/Funding"; // adjust path
import { UserProvider } from "../context/panContext";
import { CustomerProvider } from "../context/CustDetail"; // adjust path as needed
import { BasicDataProvider } from "../context/Basic";
import {PersonalDetailsProvider } from "../context/personal"
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600&display=swap"
          rel="stylesheet"
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <FundingProvider>
          <UserProvider>
            <BasicDataProvider>
              <PersonalDetailsProvider> {children} </PersonalDetailsProvider>
             
              </BasicDataProvider>
          </UserProvider>
        </FundingProvider>
      </body>
    </html>
  );
}
